[build]
target = "thumbv7em-none-eabihf"


[env]
DEFMT_LOG = "trace"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32G474RETx with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32F407VGTx"
